kinova_arm_joint_1_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: kinova_arm_joint_1
  pid: {p: 1.0, i: 0.0, d: 0.0}

kinova_arm_joint_2_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: kinova_arm_joint_2
  pid: {p: 1.0, i: 0.0, d: 0.0}

kinova_arm_joint_3_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: kinova_arm_joint_3
  pid: {p: 1.0, i: 0.0, d: 0.0}

kinova_arm_joint_4_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: kinova_arm_joint_4
  pid: {p: 1.0, i: 0.0, d: 0.0}

kinova_arm_joint_5_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: kinova_arm_joint_5
  pid: {p: 1.0, i: 0.0, d: 0.0}

kinova_arm_joint_6_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: kinova_arm_joint_6
  pid: {p: 1.0, i: 0.0, d: 0.0}
